lipreading_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url 
from django.conf.urls.static import static
from django.conf import settings

# Application urls are added to the project urls
urlpatterns = [
    path('wordquiz/quiz/', include('quizzes.urls', namespace='quizzes')),
    path('quizzes/', include('lipquiz.urls')),
    path('user/', include('users.urls')),
    path('admin/admin/', admin.site.urls),
    path('', include('selection_pages.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quizzes/urls.py
from django.urls import path
from .views import (
    QuizListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view,
)

app_name = 'quizzes'

# These application specific url patterns need to be added to the project URLs
urlpatterns = [
    path('', QuizListView.as_view(), name='main-view'),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/save/', save_quiz_view, name='save-quiz'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
]

users/urls.py
# This file has all the url mapping to their corresponding views 
#from django.conf.urls import url 
from users.views import dashboard, register
from django.urls import path, include

# names are usually used for reverse mapping where the full url path need not be specified
urlpatterns = [
    # this gives us access to all django related auth urls like login, logout etc. The urls automatically render the corresponding html pages.
    path("accounts/", include("django.contrib.auth.urls")),
    path("dashboard/", dashboard, name="dashboard"),
    path("register/", register, name="register"),
]

quizzes/models.py
from django.db import models
import random

# Create your models here.
DIFF_CHOICES = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)

class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="Duration of the quiz")
    pass_score = models.IntegerField(help_text="Minimum score required to pass", )
    difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES)

    def __str__(self):
        return f"{self.topic}--{self.name}"

    # We need to get the questions for a quiz 
    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizzes'

quizzes/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Quiz
from django.http import JsonResponse
from questions.models import Question
from results.models import Result

# Create your views here.
# This shows all the quizzes in the form of a listview 
class QuizListView(ListView):
    model = Quiz 
    template_name = 'quizzes/main.html'

# Get the quiz corresponding to the primary key
def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizzes/quiz.html', {'obj':quiz})

# Returns the quiz data view
def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})

    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })

# Save the quiz response 
def save_quiz_view(request, pk):
    questions = list()
    if request.is_ajax():
        data = request.POST
        data = dict(data.lists())
        data.pop('csrfmiddlewaretoken')
        for k in data.keys():
            question = Question.objects.get(text=k)
            questions.append(question)

        # compute the score for the user on the quiz 
        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        # In the results, we want to show the answered choice and the correct answer
        results = list()
        score_multiplier = 100 / quiz.number_of_questions
        score = 0

        for question in questions:
            answers = question.get_answers()
            for answer in answers:
                if answer.correct:
                    correct_answer = answer.text
            selected_answer = data[question.text][0]
            if correct_answer == selected_answer:
                score += 1
            results.append({str(question): {"correct_answer":correct_answer, "answered": selected_answer}})

        score_ = score_multiplier * score 
        print(f"Score : {score_}%")

        # update the results entry with the score for (user, quiz)
        Result.objects.create(quiz=quiz, user=user, score=score_)

        return JsonResponse({'passed': score_ >= quiz.pass_score, 'score': score_, 'results': results})

quizzes/templates/quizzes/main.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizzes/main.js' %}" defer></script> 
{% endblock scripts %}

{% block title %}
home
{% endblock title %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="model-body-confirm"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
        <button type="button" id="start-button" class="btn btn-success">Yes</button>
      </div>
    </div>
  </div>
</div>

<div class="h1">Quiz List</div>
<hr>
<!-- Show a button for every quiz present -->
{% for obj in object_list %}
    <button
        class="btn btn-link modal-button"
        data-pk="{{obj.pk}}"
        data-quiz="{{obj.name}}"
        data-questions="{{obj.number_of_questions}}"
        data-difficulty="{{obj.difficulty}}"
        data-time="{{obj.time}}"
        data-pass = "{{obj.pass_score}}"
        data-toggle="modal"
        data-target="#quizStartModal">
        {{obj.name}}
    </button><br>
{% endfor %}
{% endblock content %}

quizzes/templates/quizzes/quiz.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizzes/quiz.js' %}" defer></script> 
{% endblock scripts %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col">
        <b>{{obj.name}}</b>
        <p>Score required to pass: {{obj.pass_score}}</p>        
    </div>
    <div class="col text-right" id="timer-box">countdown</div>
</div>

<!-- The urls for a particular view are specified in the format - app-name:view-name -->
<a href="{% url 'quizzes:main-view' %}" class="btn btn-danger">Go back</a>

<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <!-- Populated programatically using js -->
    <div id="quiz-box"></div>
    <button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>
<div id="score-box"></div>
<div id="result-box"></div>
{% endblock content %}