lipquiz/urls.py
from django.urls import path
from . import views

app_name = 'lipquiz'

urlpatterns = [
    path('', views.VideoQuizListView.as_view(), name='lip-quiz-view'),
    path('lipread_sentences/<pk>/', views.video_quiz_view, name='video-quiz-view'),
    path('lipread_sentences/<pk>/data/', views.video_quiz_data_view, name='video-quiz-data-view'),
    path('lipread_sentences/<pk>/save/', views.video_quiz_data_save, name='video-quiz-data-save'),
    path('', views.MissingWordsQuizListView.as_view(), name='lip-missing-words-quiz-view'),
    path('lipread_missing/<pk>/', views.video_missing_words_quiz_view, name='video-missing-words-quiz-view'),
    path('lipread_missing/<pk>/data/', views.video_missing_words_quiz_data_view, name='video-missing-words-quiz-data-view'),
    path('lipread_missing/<pk>/save/', views.video_missing_words_quiz_data_save, name='video-missing-words-quiz-data-save'),
    # path('lipread_words', views.lipread_words, name='lipread-words'),
    path('lipread_missing/', views.lipread_words, name='lipread-words'),
]

lipreading_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url 
from django.conf.urls.static import static
from django.conf import settings

# Application urls are added to the project urls
urlpatterns = [
    path('wordquiz/quiz/', include('quizzes.urls', namespace='quizzes')),
    path('quizzes/', include('lipquiz.urls')),
    path('user/', include('users.urls')),
    path('admin/admin/', admin.site.urls),
    path('', include('selection_pages.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

selection_pages/urls.py
from django.urls import path
from . import views

app_name = 'selection_pages'

urlpatterns = [
    path('protocol_selection', views.index, name='lipreading-protocol-selection'),
    # path('lipread_words', views.lipread_words, name='lipread-words'),
    # path('', views.main_page, name='landing-page'),
    path('', views.main_surrogate, name='landing-surrogate')
]

users/urls.py
# This file has all the url mapping to their corresponding views 
#from django.conf.urls import url 
from users.views import dashboard, register
from django.urls import path, include

# names are usually used for reverse mapping where the full url path need not be specified
urlpatterns = [
    # this gives us access to all django related auth urls like login, logout etc. The urls automatically render the corresponding html pages.
    path("accounts/", include("django.contrib.auth.urls")),
    path("dashboard/", dashboard, name="dashboard"),
    path("register/", register, name="register"),
]

lipquiz/models.py
from django.db import models
import random

# Create your models here.
QUIZ_TYPE = (
    ('single word mcq', 'single word mcq'),
    ('single word blank with context', 'single word blank with context'),
    ('sentence with context', 'sentence with context'),
    ('sentence with blank', 'sentence with blank'),
)

DIFF_CHOICES = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)

class VideoQuiz(models.Model):
    name = models.CharField(max_length=120)
    description = models.CharField(max_length=256)
    number_of_questions = models.IntegerField() 
    time = models.IntegerField(help_text="Duration of the quiz") # in minutes 
    difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES)
    quiz_type = models.CharField(max_length=120, choices=QUIZ_TYPE)
    score_required_to_pass = models.IntegerField(help_text="Minimum score required to pass the quiz")
    is_visible = models.BooleanField(help_text="Whether the quiz is visible or not", default=False)

    def __str__(self):
        return f"{self.name}--{self.description}"
    
    def get_questions(self):
        questions = list(self.singlewordquestion_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'VideoQuizzes'


class MissingWordInSentenceQuiz(models.Model):
    
    name = models.CharField(max_length=120)
    description = models.CharField(max_length=256)
    number_of_questions = models.IntegerField() 
    time = models.IntegerField(help_text="Duration of the quiz") # in minutes 
    difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES)
    quiz_type = models.CharField(max_length=120, choices=QUIZ_TYPE)
    score_required_to_pass = models.IntegerField(help_text="Minimum score required to pass the quiz")
    is_visible = models.BooleanField(help_text="Whether the quiz is visible or not", default=False)

    def __str__(self):
        # return f"{self.name}--{self.description}"
        return f"{self.id};{self.name};{self.description};{self.number_of_questions};{self.difficulty};{self.is_visible}"
    
    def get_questions(self):
        questions = list(self.missingwordsquestion_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'MissingWordQuizzes'

lipquiz/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView
from .models import MissingWordInSentenceQuiz, VideoQuiz
from results.models import MissingWordsResult, SingleWordResult
from questions.models import MissingWordsAnswer, MissingWordsQuestion, SingleWordQuestion
from django.http import JsonResponse
import random

# View corresponding to lipreading isolated words protocol
class VideoQuizListView(ListView):
    model = VideoQuiz 
    template_name = "lipquiz/main.html"

# View corresponding to lirpeading missing words in sentences protocol 
class MissingWordsQuizListView(ListView):
    model = MissingWordInSentenceQuiz
    template_name = "lipquiz/main_missingwords.html"

# loads the quiz view corresponding to the primary key 
# in obj, the fields defined in the VideoQuiz model are loaded 
def video_quiz_view(request, pk):
    videoquiz = VideoQuiz.objects.get(pk=pk)
    return render(request, 'lipquiz/quiz.html', {'obj': videoquiz})

# load the quiz view corresponding to the primary key for the protocol 
# -- lipreading missing words in sentences 
def video_missing_words_quiz_view(request, pk):
    videoquiz = MissingWordInSentenceQuiz.objects.get(pk=pk)
    return render(request, 'lipquiz/missingword_quiz.html', {'obj': videoquiz})

# Returns the content of the quiz corresponding to the lipreading isolated words protocol
# This is used when the user navigates inside the quiz
def video_quiz_data_view(request, pk):
    videoquiz = VideoQuiz.objects.get(pk=pk)
    questions = list()
    response = list()
    for q in videoquiz.get_questions():
        answers = list()
        for a in q.get_answers():
            answers.append(a.text)
        #questions.append({str(q.pk) + " " + q.text : answers})
        print(f"Video path: {q.video_path}")
        response.append({'question': q.text, 'video_path': q.video_path, 'answer': answers})
        questions.append({q.video_path : answers})

    print(f"Response: {response}")
    return JsonResponse(response, safe=False)

# returns the content of the quiz corresponding to the protocol -- lipreading missing words in sentence
# This is used when the user is inside the quiz
def video_missing_words_quiz_data_view(request, pk):
    # we need the questions and answers corresponding to a given quiz
    videoquiz = MissingWordInSentenceQuiz.objects.get(pk=pk)
    questions = list()
    response = list()

    print(f'This function gets called when the quiz is loaded')

    # get all questions corresponding to a given video quiz
    for question in videoquiz.get_questions():
        # get the answer corresponding to the given question 
        answers = list()
        for answer in question.get_answers():
            answers.append(answer.answer)

        print(f'Answers are : {answers}')

        print(f'Video path : {question.video_path}')
        response.append({'question': question.text, 'video_path': question.video_path, 'answer': answers})
        questions.append({question.video_path: answer}) # assigning an answer to a question key (video_path)

    print(f'Response : {response}')
    return JsonResponse(response, safe=False)


def video_quiz_data_save(request, pk):
    if request.is_ajax():
        data = request.POST
        data = dict(data.lists())
        data.pop('csrfmiddlewaretoken')

        quiz = VideoQuiz.objects.get(pk=pk)
        user = request.user

        results = list()
        score = 0
        score_multiplier = 100/quiz.number_of_questions

        for q in data.keys():
            question = SingleWordQuestion.objects.get(video_path=q)
            answers = question.get_answers()
            for a in answers:
                if a.correct:
                    correct_answer = a.text
            user_answered = data[q][0]
            if correct_answer == user_answered:
                score += 1
            results.append({str(question.text):{"correct_answer":correct_answer, "answered":user_answered}})
        
        score_ = score_multiplier * score
        print(f"Score: {score_}")

        SingleWordResult.objects.create(quiz=quiz, user=user, score=score_)

        return JsonResponse({'score': score_, 'results': results})


def video_missing_words_quiz_data_save(request, pk):
    print(request.POST)
    if request.is_ajax():
        questions = list()
        data = request.POST
        data_ = dict(data.lists()) # transforms the query dict to an ordinary list
        # remove the csrfmiddlewaretoken from the dict of question-answer pair 
        data_.pop('csrfmiddlewaretoken')
        
        quiz = MissingWordInSentenceQuiz.objects.get(pk=pk)
        user = request.user

        total_questions = quiz.number_of_questions
        print(f'Number of questions in the quiz : {total_questions}')

        correct = 0
        total_questions = 0
        results = list()     

        for q in data_.keys():
            print('key: ', q)
            question = MissingWordsQuestion.objects.get(video_path=q)
            answers = question.get_answers()
            user_answered = data[q].lower()
            answer = answers[0].answer.lower()
            print(f'Correct answer : {answer}, user answered : {user_answered}')
            # questions.append(question)

            # for each question if the answered question is the correct answer 
            if answer == user_answered:
                print(f'{answer.lower()}, {user_answered.lower()}')
                correct += 1

            total_questions += 1

            results.append({str(question.text):{"correct_answer":answer, "answered":user_answered}})

        score = (correct/total_questions)*100
        print(f'Total questions : {total_questions}, correctly answered : {correct}, score is : {score}')
        
        MissingWordsResult.objects.create(quiz=quiz, user=user, score=score)

    return JsonResponse({'score': score, 'results': results})


def lipread_words(request):
    print(f'Inside this function')
    lipread_words_quizzes = MissingWordInSentenceQuiz.objects.all().filter(is_visible=True)
    print(f'Lipread word quizzes : {lipread_words_quizzes}')

    # randomly choose one quiz from the list of quizzes 
    words_quiz_list = list(lipread_words_quizzes)
    random.shuffle(words_quiz_list)
    words_quiz = words_quiz_list[0]
    
    print(f'Word quiz list : {str(words_quiz)}')

    pk, name, description, num_questions, difficulty, _ = str(words_quiz).split(';')
    print(f'Fields are : {type(pk)}, {name}, {description}')

    pk = int(pk)
    print(f'The primary key is : {pk}, and type is : {type(pk)}')

    videoquiz = VideoQuiz.objects.get(id=pk)
    print(f'Video quiz is : {videoquiz}')
    return render(request, 'lipquiz/missingword_quiz.html', {'obj': videoquiz})


def lipread_sentences(request):
    pass


def lipread_missing(request):
    pass

lipquiz/templates/lipquiz/main.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'lipquiz/main.js' %}" defer></script>
{% endblock scripts %}

{% block content %}
{% if user.is_authenticated %}
<!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="model-body-confirm"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
          <button type="button" id="start-button" class="btn btn-success">Yes</button>
        </div>
      </div>
    </div>
</div>

<div class="h1">Quiz List</div>
<hr>

<!-- Show a button link for every quiz present-->
<ul>
{% for obj in object_list %}
    {% if obj.is_visible %}
      <li><button class="btn btn-link start-quiz-button"
          data-quiz="{{obj.name}}"
          data-pk="{{obj.pk}}"
          data-questions="{{obj.number_of_questions}}"
          data-description="{{obj.description}}"
          data-difficulty="{{obj.difficulty}}"
          data-quiz-type="{{obj.quiz_type}}"
          data-toggle="modal"
          data-target="#quizStartModal">
          {{obj.name}}
      </button></li><br>
    {% endif %}
{% endfor %}
</ul>
{% else %}
    <p>Please <a href="{% url 'login' %}">login</a> to view the Quizzes</p>
{% endif %}
{% endblock content %}

lipquiz/templates/lipquiz/main_missingwords.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'lipquiz/main.js' %}" defer></script>
{% endblock scripts %}

{% block content %}
{% if user.is_authenticated %}
<!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="model-body-confirm"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
          <button type="button" id="start-button" class="btn btn-success">Yes</button>
        </div>
      </div>
    </div>
</div>

<div class="h1">Quiz List</div>
<hr>

<!-- Show a button link for every quiz present-->
<ul>
{% for obj in object_list %}
    {% if obj.is_visible %}
      <li><button class="btn btn-link start-quiz-button"
          data-quiz="{{obj.name}}"
          data-pk="{{obj.pk}}"
          data-questions="{{obj.number_of_questions}}"
          data-description="{{obj.description}}"
          data-difficulty="{{obj.difficulty}}"
          data-quiz-type="{{obj.quiz_type}}"
          data-toggle="modal"
          data-target="#quizStartModal">
          {{obj.name}}
      </button></li><br>
    {% endif %}
{% endfor %}
</ul>
{% else %}
    <p>Please <a href="{% url 'login' %}">login</a> to view the Quizzes</p>
{% endif %}
{% endblock content %}

lipquiz/templates/lipquiz/missingword_quiz.html
{% extends "base.html" %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>

{% block scripts %}
    <script src="{% static 'lipquiz/quiz_missingwords.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
    <div class="heading">
        <b>Quiz: {{obj.name}}</b>
    </div>
    <br>

    <a href="{% url 'selection_pages:lipreading-protocol-selection' %}" class="btn btn-danger goback">Go back</a>

    <form autocomplete="off" id='quiz-form' class='mt-3 mb-3'>
        {% csrf_token %}
        <div id="quiz-box"></div>
        <div id="submit-quiz-btn-id" class="submit-btn-div">
            <button type="submit" class="btn btn-primary mt-3 submit-quiz-btn">Submit</button>
        </div>
    </form>

<div id="score-box"></div>
<div id="time-box"></div>
<div id="replays-box"></div>
<div id="result-box"></div>
<a href="" class="try-again not-visible" id="try-again-btn"><img id="try-again-img" src="/static/try_again.png">Try Again </a>
{% else %}
    <p>Please <a href="{% url 'login' %}">login</a> to attempt the Quiz</p>
{% endif %}
{% endblock content %}

lipquiz/templates/lipquiz/quiz.html
{% extends "base.html" %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>

{% block scripts %}
    <script src="{% static 'lipquiz/quiz.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
    <div class="heading">
        <b>Quiz: {{obj.name}}</b>
    </div>
    <br>

    <a href="{% url 'selection_pages:lipreading-protocol-selection' %}" class="btn btn-danger goback">Go back</a>

    <form id='quiz-form' class='mt-3 mb-3'>
        {% csrf_token %}
        <div id="quiz-box"></div>
        <div id="submit-quiz-btn-id" class="submit-btn-div">
            <button type="submit" class="btn btn-primary mt-3 submit-quiz-btn">Submit</button>
        </div>
    </form>

<div id="score-box"></div>
<div id="time-box"></div>
<div id="replays-box"></div>
<div id="result-box"></div>
<a href="" class="try-again not-visible" id="try-again-btn"><img id="try-again-img" src="/static/try_again.png">Try Again </a>
{% else %}
    <p>Please <a href="{% url 'login' %}">login</a> to attempt the Quiz</p>
{% endif %}
{% endblock content %}