lipreading_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url 
from django.conf.urls.static import static
from django.conf import settings

# Application urls are added to the project urls
urlpatterns = [
    path('wordquiz/quiz/', include('quizzes.urls', namespace='quizzes')),
    path('quizzes/', include('lipquiz.urls')),
    path('user/', include('users.urls')),
    path('admin/admin/', admin.site.urls),
    path('', include('selection_pages.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

selection_pages/urls.py
from django.urls import path
from . import views

app_name = 'selection_pages'

urlpatterns = [
    path('protocol_selection', views.index, name='lipreading-protocol-selection'),
    # path('lipread_words', views.lipread_words, name='lipread-words'),
    # path('', views.main_page, name='landing-page'),
    path('', views.main_surrogate, name='landing-surrogate')
]

users/urls.py
# This file has all the url mapping to their corresponding views 
#from django.conf.urls import url 
from users.views import dashboard, register
from django.urls import path, include

# names are usually used for reverse mapping where the full url path need not be specified
urlpatterns = [
    # this gives us access to all django related auth urls like login, logout etc. The urls automatically render the corresponding html pages.
    path("accounts/", include("django.contrib.auth.urls")),
    path("dashboard/", dashboard, name="dashboard"),
    path("register/", register, name="register"),
]

selection_pages/models.py
from django.db import models

# Create your models here.

selection_pages/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView
from django.http import JsonResponse, HttpResponse

def index(request):
    return render(request, 'selection_pages/select_protocol.html')

def main_surrogate(request):
    return render(request, 'selection_pages/main_surrogate.html')

def main_page(request):
    return render(request, 'selection_pages/main_page.html')

def lipread_words(request):
    # One of the functions corresponding to lirpeading words is loaded
    return render(request, 'selection_pages/quiz_page.html')

selection_pages/templates/selection_pages/select_protocol.html
<h1 class="heading">Select lipreading training protocol</h1>
{% extends "base.html" %}

{% load static %}

{% block scripts %}
    <script src="{% static 'selection_pages/protocol_selection.js' %}" defer></script>
{% endblock scripts %}

{% block content %}
{% if user.is_authenticated %}
<link rel="stylesheet" type="text/css" href="{% static 'selection_pages/style.css' %}"/>

<a href="{% url 'selection_pages:landing-surrogate' %}" class="btn btn-danger goback">Go back</a>

<div class="protocol_selection_wrapper">
  <div class="protocol_selection_label_wrapper">
    <label class="protocol_selection_label">
      <span class="protocol_name">Lipread<br>Words</span>
      <input type="radio" name="test" value="lipread_words" class="ans" checked>
      <img src="static/images/lipread_words.png" alt="Lipread isolated words">
    </label>
    
    <label class="protocol_selection_label">
      <span class="protocol_name">Lipread<br>Sentences</span>
      <input type="radio" name="test" value="lipread_sentences" class="ans">
      <img src="static/images/lipread_sentence.png" alt="Lipread sentence with context">
    </label>

    <label class="protocol_selection_label">
      <span class="protocol_name">Lipread Missing Words in Sentences</span>
      <input type="radio" name="test" value="lipread_missing" class="ans">
      <img src="static/images/lipread_missing.png" alt="Lipread missing words in sentences">
    </label>
  </div>

    <!-- The url selected depends on the radiobutton that was selected before submit -->

    <!-- <button id='protocol_select_button' onclick="location.href = '/quizzes'">Click</button> -->
    <br/>
    <button id='protocol_select_button' class="btn btn-primary mt-3 submit-quiz-btn">Submit</button>
  </div>

  <!-- Button trigger modal -->
  <!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Launch demo modal
  </button> -->

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
  {% else %}
    <p>Please <a href="{% url 'login' %}">login</a> to view the Quizzes</p>
  {% endif %}
  {% endblock content %}